server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/TicketRealm
          jwk-set-uri: http://localhost:8180/realms/TicketRealm/protocol/openid-connect/certs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/v1/tickets/**
        - id: ticket-service-reports
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/v1/reports/**
        - id: support-service
          uri: lb://SUPPORT-SERVICE
          predicates:
            - Path=/api/v1/departments/**,/api/v1/teams/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/