server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/v1/tickets/**
        - id: ticket-service-reports
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/api/v1/reports/**
        - id: support-service
          uri: lb://SUPPORT-SERVICE
          predicates:
            - Path=/api/v1/departments/**,/api/v1/teams/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        # --- Swagger/OpenAPI api-docs proxy route'lari ---
        - id: ticket-service-api-docs
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/ticket-service/v3/api-docs
          filters:
            - RewritePath=/ticket-service/v3/api-docs, /v3/api-docs
        - id: support-service-api-docs
          uri: lb://SUPPORT-SERVICE
          predicates:
            - Path=/support-service/v3/api-docs
          filters:
            - RewritePath=/support-service/v3/api-docs, /v3/api-docs
        - id: user-service-api-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/v3/api-docs, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Ticket Service
        url: /ticket-service/v3/api-docs
      - name: Support Service
        url: /support-service/v3/api-docs
      - name: User Service
        url: /user-service/v3/api-docs
    path: /swagger-ui.html
  api-docs:
    enabled: true
