server:
  port: 8082

spring:
  application:
    name: notification-service
  

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: notification-service
            client-secret: vIyH8ugPFVrrFU9EzNg0Y6t94vHN5ycy
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/TicketRealm

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group-v2
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ticketapp.notification.dto.TicketEventDto

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/