server:
  port: 8084

spring:
  application:
    name: support-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/TicketRealm
  # --- VERİTABANI AYARLARI ---
  datasource:
    # Docker 5432 portunu dışarı açtığı için 'localhost' kullanıyoruz
    url: jdbc:postgresql://localhost:5432/supportdb
    username: admin      # docker-compose.yml dosyasındaki ile AYNI olmalı
    password: password   # docker-compose.yml dosyasındaki ile AYNI olmalı
    driver-class-name: org.postgresql.Driver

  # --- JPA / HIBERNATE AYARLARI ---
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Entity sınıflarını otomatik tabloya çevirir
    show-sql: true      # SQL sorgularını konsolda görelim

logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    org.springframework.cloud.gateway: TRACE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/